2ndLife/Controllers/CategoryController.cs
using _2ndLife.Data;
using _2ndLife.Models;
using _2ndLife.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;

namespace _2ndLife.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryData db;
        public CategoryController(ICategoryData db)
        {
            this.db = db;
        }


        // GET: Category
        public ActionResult Index()
        {
            var model = db.GetAll();
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        // GET: Category/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Add(category);
                return RedirectToAction("Details", new { id = category.CategoryId });
            }
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
              return NotFound(); 
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Update(category);
                return RedirectToAction("Details", new { id = category.CategoryId });
            }
            return View();
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Get(id);
            if (model == null)
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(int id, IFormCollection form)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

2ndLife/Controllers/ConversationController.cs
using _2ndLife.Areas.Identity;
using _2ndLife.Models;
using _2ndLife.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _2ndLife.Controllers
{
    public class ConversationController : Controller
    {

        private readonly IConversationData context;
        private readonly UserManager<AppUser> userContext;

        public ConversationController(IConversationData context, UserManager<AppUser> userContext)
        {
            this.context = context;
            this.userContext = userContext;
        }

        public IActionResult Index(int id)
        {
            Conversation conv = context.Get(id);
            return View(conv);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string User1, string User2)
        {
            AppUser u1 = await userContext.GetUserAsync(User);
            AppUser u2 = await userContext.FindByIdAsync(User2);
            
            Conversation conversation = context.Get(User1, User2, u1, u2);

            return View(conversation);
        }

        [HttpPost]
        public ActionResult Create(string messageContent, int id)
        {
            //if(String.IsNullOrEmpty(restaurant.Name))
            //{
            //    ModelState.AddModelError(nameof(restaurant.Name), "The name is required");
            //}

            Conversation conv = context.Get(id);
            Message message = new() {
                Conversation = conv,
                MessageContent = messageContent,
                ConversationId = id.ToString(),
                Time = DateTime.Now,
                User = userContext.GetUserAsync(User).Result
            };
            if(conv.Messages == null)
            {
                conv.Messages = new List<Message>();
            }
            
            conv.Messages.Add(message);
            //context.Add(message);
            context.Add(conv);

            if (ModelState.IsValid)
            {
                //db.Add(offer);
                return View("Index", conv);
            }
            return View("Index", conv);
        }

        public IActionResult All()
        {
            IEnumerable<Conversation> conversations = context.GetAllConversationByUser(userContext.GetUserAsync(User).Result);
            return View(conversations);
        }


    }
}

2ndLife/Controllers/OffersController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using _2ndLife.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using _2ndLife.ViewModels;
using _2ndLife.Areas.Identity;
using _2ndLife.Services;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace _2ndLife.Controllers
{
    public class OffersController : Controller
    {
        private readonly IOfferData db;
        private readonly UserManager<AppUser> userContext;

        public OffersController(IOfferData db, UserManager<AppUser> userContext)
        {
            this.db = db;
            this.userContext = userContext;
        }

        public IActionResult Index(int? CategoryId)
        {
            ViewData["CategoryId"] = new SelectList(db.GetAllCategories(), "CategoryId", "CategoryName", "Select");
            List<Offer> list = db.filteredCategory(CategoryId);
            return View(list);
        }
        
        [Authorize]
        public IActionResult Details(int id)
        {
            var offer = db.Get(id);
            
            ViewBag.User1 = userContext.GetUserId(User).ToString();
            ViewBag.User2 = offer.UserId.ToString();

            var category = db.GetCategory(offer.CategoryId);
            offer.Category = category;
            if(offer == null || category == null)
            {
                return View("NotFound");
            }
            return View(offer);
        }

        [Authorize]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var u = await userContext.GetUserAsync(User);
            if (!u.isBanned)
            {
                ViewBag.CategoryId = new SelectList(db.GetAllCategories(), "CategoryId", "CategoryName");
                return View();
            }
            else
            {
                return View("NotAuthorized");
            }
        }

        //model binding
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OfferViewModel offer)
        {
            ViewBag.CategoryId = new SelectList(db.GetAllCategories(), "CategoryId", "CategoryName");

            if (ModelState.IsValid)
            {
                db.Add(offer, userContext.GetUserId(User));
                return RedirectToAction("Index");
            }
            
            return View();
        }

        
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var u = await userContext.GetUserAsync(User);
            if (!u.isBanned) { 

                var model = db.GetViewModel(id);
            if (userContext.GetUserId(User).ToString() == model.UserId)
            {
            ViewBag.CategoryId = new SelectList(db.GetAllCategories(), "CategoryId", "CategoryName");
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
            else
                return View("NotFound");
            }
            else
            {
                return View("NotAuthorized");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(OfferViewModel offer)
        {
            if (ModelState.IsValid)
            {
                db.Update(offer);
                return RedirectToAction("Details", new { id = offer.OfferId });
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = db.Get(id);
            if(model == null )
            {
                return View("NotFound");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id, IFormCollection form)
        {
            db.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Report(int id)
        {
            db.Report(id);

            return RedirectToAction("Index");
        }

        public IActionResult Unreport(int id)
        {
            db.Unreport(id);

            return RedirectToAction("Index");
        }

        public IActionResult Ban(int id)
        {
            db.Ban(id);

            return RedirectToAction("Index");
        }



    }
}

2ndLife/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Identity
@using _2ndLife.Areas.Identity
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 2ndLife</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-mint.css" />
    <style>
        body {
            padding-top: 150px;
            background-color: #fcf5cb;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-navbar border-bottom box-shadow fixed-top mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img alt="Brand" src="~/logo.png" height="95" width="153"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-success h2" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated == true)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-success h2" asp-area="" asp-controller="Conversation" asp-action="All">Messages</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated == true)
                        {
                            @if (UserManager.GetRolesAsync(UserManager.GetUserAsync(User).Result).Result.Contains("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-success h2" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                </li>
                            }
                        }
                            <li class="nav-item">
                                <a class="nav-link text-success h2" asp-area="" asp-controller="Offers" asp-action="Index">Offers</a>
                            </li>
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - 2ndLife - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>